### ISSUE TITLE
Clean exit with LAMMPS

### ISSUE THREAD

**Issue by brunoduran** [cosmo-epfl/i-pi-dev#192]
I cannot use I-PI with LAMMPS without getting an error code. I-PI seems to need an extra iteration to close the server but if you actually do the the extra iteration LAMMPS registers an error. Let's say that we have `N` timesteps and `P` beads.

```xml
<total_steps>N</total_steps>
...
<initialize nbeads='P'>
```
We need P * (N + 1) force evaluations.

```
run P * (N + 1)
```
Everything seems correct, but the server does not go down. But if we add an additional step:

```
run P * (N + 1) + 1
```

The server closes, but LAMMPS register an error:

```
ERROR on proc 0: Got EXIT message from i-PI. Now leaving! (../fix_ipi.cpp:300)  
```

Is there any way to do a "clean" exit with LAMMPS without manually killing the I-PI server?

**Comment by ceriottm** [comment]
Uhm. I think we had just thought that the normal course of action for i-PI
exiting before run XXXX had finished was to throw an error. Simple answer
would be to use exactly the same run value in LAMMPS as the force
evaluations you need in i-PI (most likely nsteps+1). What would be your
expected behavior and why would you need LAMMPS to carry on rather than
exit?

**Comment by brunoduran** [comment]
> Simple answer would be to use exactly the same run value in LAMMPS as the force evaluations you need in i-PI (most likely nsteps+1).

I do not think that it is possible, at least with LAMMPS. If you want to finish the simulation you get a status code of 1 in you clients.

LAMMPS evaluations <= Total number of evaluations --> I-PI server does not shut down
LAMMPS evaluations >   Total number of evaluations --> Clients end with a status code of 1

It is not an important issue, but I can upload a reproducible example if you want.

**Comment by ceriottm** [comment]
OK, so basically this is a (minor) issue on the LAMMPS interface side. I
guess the main problem might be it makes it hard to detect whether an error
has occurred during the simulation.  Honestly we're a bit snowed under
making the v2.0 release of i-PI so this is not top of the list - but if you
can see a simple way to change the driver to exit gracefully rather than
brutally, I'd be glad to package that into a parch and pass it on to Axel
and the other LAMMPS developers.
